<?xml version="1.0" encoding="utf-8"?><Database Name="TechMate_db" Class="linq2sqlDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=tcp:techmatedbserver1.database.windows.net,1433;Initial Catalog=TechMate_db;Persist Security Info=False;User ID=TechMate;MultipleActiveResultSets=False;Connect Timeout=30;Encrypt=True;TrustServerCertificate=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="TechMate_dbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="surname" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="cellNo" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="gender" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="userType" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Build" Member="Builds">
    <Type Name="Build">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="category" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="compatibilityStatus" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="baseBuild_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ram_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="storage_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="graphics_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cpu_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="totalPrice" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Component" Member="Components">
    <Type Name="Component">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="price" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="availability" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="image" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="compatibility" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="build_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="category" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="intPriceFormat" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CartItems" Member="CartItems">
    <Type Name="CartItem">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="component_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cart_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DeliveryAddress" Member="DeliveryAddresses">
    <Type Name="DeliveryAddress">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="country" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="province" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="suburb" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="streetUnit" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="zipCode" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="user_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Order]" Member="Orders">
    <Type Name="Order">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="cartId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="paymentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="userAddressId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="userId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="dateCreated" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="paymentMade" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="orderStatus" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Cart" Member="Carts">
    <Type Name="Cart">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="build_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="totalPrice" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="totalDiscountSaved" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Compatibility" Member="Compatibilities">
    <Type Name="Compatibility">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="desktopCase_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ramType" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="storageType" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="cpuType" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="graphicsType" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>